Improve codespace secrets approach
mysociety/theyworkforyou pull request #1798
Opened 2024-06-09 19:13 UTC by ajparsons

Features like the donate page and election lookup need external API keys, which doesn't work nicely with the docker setup because the conf/general is recreated each time the docker is opened (rather than created). 

This PR:

- Adjusts docker setup so that system environmental variables populate the `conf/general` file.
- Adjust 'devcontainer.json' to prompt codespaces users to setup the (optional) keys in their user codespace secrets store.

![image](https://github.com/mysociety/theyworkforyou/assets/8157058/c9f9915b-54a4-431c-a770-35eee821628c)

2024-09-06 19:04 UTC, dracos requested changes
Some typos to fix I think is all

2024-09-06 19:04 UTC, dracos commented on docker-compose.yml
> +      RECAPACHA_SITE_KEY: ${RECAPACHA_SITE_KEY:-}
Some spelling mistakes in here

2024-09-24 08:34 UTC, ajparsons commented on docker-compose.yml
> +      RECAPACHA_SITE_KEY: ${RECAPACHA_SITE_KEY:-}
Should be fixed!

2024-10-04 09:06 UTC, dracos commented on docker-compose.yml
> +      RECAPACHA_SITE_KEY: ${RECAPACHA_SITE_KEY:-}
And still mispelled here

2024-10-04 11:54 UTC, ajparsons commented
Sorry sorry - should all be fixed.

2024-10-04 11:58 UTC, dracos approved these changes
Thanks. Didn't want that to cause some confusion down the line somewhere, if unlikely :)

2024-10-07 10:05 UTC, merged